### ISSUE TITLE
Randao message_hash is not a hash

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#926] opened 2019-04-15 07:00 UTC
The `message_hash` supplied to [per-block-processing/randao](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#randao) is not actually a hash, it's just the little-endian encoding of `get_current_epoch(state)`.

I suspect the intention is for it to be a hash.

See #859 for reference.

**Comment by ralexstokes** [comment] 2019-04-15 12:10
my understanding here is that given the relative cost of cryptographic signature operations, we usually want to push as little data as possible through a given signing algorithm. however usually we want to produce a commitment to data that is larger than a given digest size (e.g. 32 bytes). this tension is usually resolved by signing the hash of the input data.

and following this "usual" procedure, it makes sense to call this parameter to this function a `message_hash`.

i interpret this use in the spec to take some creative liberties wrt the input data being a hash or not. in this case we just pad the current epoch to 32 bytes and proceed normally. i would think we want to avoid introducing another hashing here, just to avoid the additional cost of computing the hash (when just the serialized integer will do).

if we agree that we can use the plain serialization in lieu of the hash then we could still argue that we change the name of this function parameter. i've seen this type of flexibility around the name employed in other cryptography software so don't think its worth changing imo. this same question came up in another issue on this repo (or possibly gitter) some months ago so that would actually be motivation for a change.

**Comment by JustinDrake** [comment] 2019-04-15 13:14
> I suspect the intention is for it to be a hash.

The logic is correct but I agree the typing is awkward. To fix the type mismatch, it's probably more natural to define a `RandaoReveal` object as

```python
{
    epoch: uint64,
    signature: bytes96,
}
```

and then `assert bls_verify(proposer.pubkey, signing_root(reveal), reveal.signature, domain)`. See the discussion [here](https://github.com/ethereum/eth2.0-specs/pull/865#issuecomment-479137921).

**Comment by djrtwo** [comment] 2019-04-17 23:51
`signing_root(reveal)` would still just be a little endian encoding of `get_current_epoch(state)`.

**Comment by JustinDrake** [comment] 2019-04-19 03:44
The spec now has [`hash_tree_root(get_current_epoch(state))`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#randao) which is the intended behaviour :)

I may introduce a `RandaoReveal` object later for cleanliness.

**Closed by JustinDrake** 2019-04-19 03:44 UTC
